name: Publish Package

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: https://registry.npmjs.org/
            - name: Install dependencies
              run: |
                npm i -g pnpm @antfu/ni
                nci
            - name: Run test
              run: nr test --if-present
            - name: Build
              run: npm run build
            - name: echo token
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                echo secrets.NPM_TOKEN
                echo  secrets.GIT_TOKEN 

            - name: Publish
              if: github.repository == 'vecmat/vite-plugin-autorouter'
              uses: mikeal/merge-release@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
